name = "asesorias-api-proxy"
main = "src/index.js"
compatibility_date = "2026-04-01"

[vars]
ALLOWED_ORIGIN = "https://asesoriasas.com"

[[d1_databases]]
binding = "DB"
database_name = "asesorias-db"
database_id = "e5d54c57-954c-4b06-969b-ca587ac70bdb"
